apiVersion: v1
items:
- apiVersion: machineconfiguration.openshift.io/v1
  kind: KubeletConfig
  metadata:
    annotations:
      machineconfiguration.openshift.io/mc-name-suffix: ""
    creationTimestamp: "2023-11-07T04:44:44Z"
    finalizers:
    - 99-master-generated-kubelet
    - 99-worker-generated-kubelet
    generation: 1
    name: dynamic-node
    resourceVersion: "47584"
    uid: aa7b341d-bc9f-4f10-99bd-82382a5a1cad
  spec:
    autoSizingReserved: true
    machineConfigPoolSelector:
      matchExpressions:
      - key: machineconfiguration.openshift.io/mco-built-in
        operator: Exists
  status:
    conditions:
    - lastTransitionTime: "2023-11-07T04:58:17Z"
      message: Success
      status: "True"
      type: Success
kind: List
metadata:
  resourceVersion: ""
