apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: Proxy
  metadata:
    creationTimestamp: "2023-11-07T04:18:11Z"
    generation: 1
    name: cluster
    resourceVersion: "639"
    uid: b9d27303-040d-42ad-8061-a036aa5474c6
  spec:
    trustedCA:
      name: ""
  status: {}
kind: List
metadata:
  resourceVersion: ""
