- apiVersion: operator.openshift.io/v1
  kind: DNS
  manifest: ./default/dns.yaml
- apiVersion: machineconfiguration.openshift.io/v1
  kind: KubeletConfig
  manifest: ./default/kubeletconfig.yaml
- apiVersion: operator.openshift.io/v1alpha1
  kind: ImageContentSourcePolicy
  manifest: ./default/imagecontentresourcepolicy.yaml
- apiVersion: config.openshift.io/v1
  kind: Proxy
  manifest: ./default/proxy.yaml
- apiVersion: machineconfiguration.openshift.io/v1
  kind: ContainerRuntimeConfig
  manifest: ./default/containerruntimeconfig.yaml
- apiVersion: machineconfiguration.openshift.io/v1
  kind: MachineConfigPool
  manifest: ./default/mastermachineconfigpool.yaml
  ignore:
    - configuration.name
- apiVersion: machineconfiguration.openshift.io/v1
  kind: MachineConfigPool
  manifest: ./default/workermachineconfigpool.yaml
  ignore:
    - configuration.name
