apiVersion: v1
items:
  - apiVersion: operator.openshift.io/v1alpha1
    kind: ImageContentSourcePolicy
    metadata:
      creationTimestamp: "2023-09-12T10:41:17Z"
      generation: 1
      name: image-policy-0
      resourceVersion: "971"
      uid: e90ac741-4cc9-4707-ab64-0f429d4e22df
    spec:
      repositoryDigestMirrors:
        - mirrors:
            - arosvc.azurecr.io/openshift-release-dev/ocp-release
          source: quay.io/openshift-release-dev/ocp-release
  - apiVersion: operator.openshift.io/v1alpha1
    kind: ImageContentSourcePolicy
    metadata:
      creationTimestamp: "2023-09-12T10:41:17Z"
      generation: 1
      name: image-policy-1
      resourceVersion: "996"
      uid: 8366be98-4e02-4252-b970-b7af77df9143
    spec:
      repositoryDigestMirrors:
        - mirrors:
            - arosvc.azurecr.io/openshift-release-dev/ocp-release-nightly
          source: quay.io/openshift-release-dev/ocp-release-nightly
  - apiVersion: operator.openshift.io/v1alpha1
    kind: ImageContentSourcePolicy
    metadata:
      creationTimestamp: "2023-09-12T10:41:18Z"
      generation: 1
      name: image-policy-2
      resourceVersion: "1002"
      uid: b887dcf6-8a85-4ee6-82cc-49a43d7c01af
    spec:
      repositoryDigestMirrors:
        - mirrors:
            - arosvc.azurecr.io/openshift-release-dev/ocp-v4.0-art-dev
          source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
kind: List
metadata:
  resourceVersion: ""