apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  creationTimestamp: "2023-08-29T10:15:47Z"
  generation: 3
  labels:
    aro.openshift.io/limits: ""
    machineconfiguration.openshift.io/mco-built-in: ""
    pools.operator.machineconfiguration.openshift.io/worker: ""
  name: worker
  resourceVersion: "38909"
  uid: 9ffd2a25-675d-423c-a971-061a141a6747
spec:
  configuration:
    name: rendered-worker-dc1b500ba088f2a07c7e88fbfe53b58a
    source:
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 00-worker
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 01-worker-container-runtime
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 01-worker-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 90-aro-worker-registries
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-worker-aro-dns
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-worker-generated-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-worker-generated-registries
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-worker-ssh
  machineConfigSelector:
    matchLabels:
      machineconfiguration.openshift.io/role: worker
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker: ""
  paused: false
status:
  conditions:
    - lastTransitionTime: "2023-08-29T10:16:26Z"
      message: ""
      reason: ""
      status: "False"
      type: RenderDegraded
    - lastTransitionTime: "2023-08-29T10:16:31Z"
      message: ""
      reason: ""
      status: "False"
      type: NodeDegraded
    - lastTransitionTime: "2023-08-29T10:16:31Z"
      message: ""
      reason: ""
      status: "False"
      type: Degraded
    - lastTransitionTime: "2023-08-29T10:46:30Z"
      message: All nodes are updated with rendered-worker-dc1b500ba088f2a07c7e88fbfe53b58a
      reason: ""
      status: "True"
      type: Updated
    - lastTransitionTime: "2023-08-29T10:46:30Z"
      message: ""
      reason: ""
      status: "False"
      type: Updating
  configuration:
    name: rendered-worker-dc1b500ba088f2a07c7e88fbfe53b58a
    source:
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 00-worker
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 01-worker-container-runtime
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 01-worker-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 90-aro-worker-registries
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-worker-aro-dns
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-worker-generated-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-worker-generated-registries
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-worker-ssh
  degradedMachineCount: 0
  machineCount: 3
  observedGeneration: 3
  readyMachineCount: 3
  unavailableMachineCount: 0
  updatedMachineCount: 3