apiVersion: v1
items:
- apiVersion: operator.openshift.io/v1alpha1
  kind: ImageContentSourcePolicy
  metadata:
    creationTimestamp: "2023-11-06T08:58:55Z"
    generation: 1
    name: image-policy-0
    resourceVersion: "1471"
    uid: 9c6eb6d1-0060-439c-a0ee-74f3df166bed
  spec:
    repositoryDigestMirrors:
    - mirrors:
      - arosvc.azurecr.io/openshift-release-dev/ocp-release
      source: quay.io/openshift-release-dev/ocp-release
- apiVersion: operator.openshift.io/v1alpha1
  kind: ImageContentSourcePolicy
  metadata:
    creationTimestamp: "2023-11-06T08:58:56Z"
    generation: 1
    name: image-policy-1
    resourceVersion: "1475"
    uid: c29e4b3c-be8b-4929-9c79-cac4b80b1a0a
  spec:
    repositoryDigestMirrors:
    - mirrors:
      - arosvc.azurecr.io/openshift-release-dev/ocp-release-nightly
      source: quay.io/openshift-release-dev/ocp-release-nightly
- apiVersion: operator.openshift.io/v1alpha1
  kind: ImageContentSourcePolicy
  metadata:
    creationTimestamp: "2023-11-06T08:58:56Z"
    generation: 1
    name: image-policy-2
    resourceVersion: "1476"
    uid: 2b996b88-4fa5-43a0-a0df-2b20b23874e9
  spec:
    repositoryDigestMirrors:
    - mirrors:
      - arosvc.azurecr.io/openshift-release-dev/ocp-v4.0-art-dev
      source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
kind: List
metadata:
  resourceVersion: ""
