apiVersion: v1
items:
- apiVersion: operator.openshift.io/v1
  kind: DNS
  metadata:
    creationTimestamp: "2023-11-06T09:02:51Z"
    finalizers:
    - dns.operator.openshift.io/dns-controller
    generation: 1
    name: default
    resourceVersion: "107914"
    uid: 4f14d53b-1a1e-48b4-980b-a1c9f8cee17d
  spec:
    logLevel: Normal
    nodePlacement: {}
    operatorLogLevel: Normal
    upstreamResolvers:
      policy: Sequential
      upstreams:
      - port: 53
        type: SystemResolvConf
  status:
    clusterDomain: cluster.local
    clusterIP: 172.30.0.10
    conditions:
    - lastTransitionTime: "2023-11-06T09:21:55Z"
      message: Enough DNS pods are available, and the DNS service has a cluster IP
        address.
      reason: AsExpected
      status: "False"
      type: Degraded
    - lastTransitionTime: "2023-11-06T11:34:04Z"
      message: All DNS and node-resolver pods are available, and the DNS service has
        a cluster IP address.
      reason: AsExpected
      status: "False"
      type: Progressing
    - lastTransitionTime: "2023-11-06T09:03:09Z"
      message: The DNS daemonset has available pods, and the DNS service has a cluster
        IP address.
      reason: AsExpected
      status: "True"
      type: Available
    - lastTransitionTime: "2023-11-06T09:02:52Z"
      message: DNS Operator can be upgraded
      reason: AsExpected
      status: "True"
      type: Upgradeable
kind: List
metadata:
  resourceVersion: ""
