apiVersion: v1
items:
- apiVersion: operator.openshift.io/v1
  kind: DNS
  metadata:
    creationTimestamp: "2023-11-07T08:27:44Z"
    finalizers:
    - dns.operator.openshift.io/dns-controller
    generation: 1
    name: default
    resourceVersion: "247377"
    uid: 02da0c29-cb8a-470b-86c6-9d10ae8783ce
  spec:
    cache:
      negativeTTL: 0s
      positiveTTL: 0s
    logLevel: Normal
    nodePlacement: {}
    operatorLogLevel: Normal
    upstreamResolvers:
      policy: Sequential
      transportConfig: {}
      upstreams:
      - port: 53
        type: SystemResolvConf
  status:
    clusterDomain: cluster.local
    clusterIP: 172.30.0.10
    conditions:
    - lastTransitionTime: "2023-11-07T08:52:41Z"
      message: Enough DNS pods are available, and the DNS service has a cluster IP
        address.
      reason: AsExpected
      status: "False"
      type: Degraded
    - lastTransitionTime: "2023-11-07T13:56:30Z"
      message: All DNS and node-resolver pods are available, and the DNS service has
        a cluster IP address.
      reason: AsExpected
      status: "False"
      type: Progressing
    - lastTransitionTime: "2023-11-07T08:28:01Z"
      message: The DNS daemonset has available pods, and the DNS service has a cluster
        IP address.
      reason: AsExpected
      status: "True"
      type: Available
    - lastTransitionTime: "2023-11-07T08:27:45Z"
      message: DNS Operator can be upgraded
      reason: AsExpected
      status: "True"
      type: Upgradeable
kind: List
metadata:
  resourceVersion: ""
